---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hexagon

resources:
  - ../base

configMapGenerator:
- name: loadgenerator-config
  files:
  - script.js=script.js
- name: loadgenerator-options-config
  files:
  - options.json=options.json

generatorOptions:
  disableNameSuffixHash: true
